---
- name: "create Cell:{{ item.row }}{{ item.column }}"
  platform42.neo4j.vertex:
    neo4j_uri: "{{ NEO4J_URI }}"
    database: "{{ NEO4J_DATABASE }}"
    username: "{{ NEO4J_USERNAME }}"
    password: "{{ NEO4J_PASSWORD }}"
    label: Cell
    entity_name: "C{{ item.row }}{{ item.column }}"
    state: PRESENT
    properties:
      row: 
        type: int
        value: "{{ item.row }}"
      column: 
        type: int
        value: "{{ item.column }}"
      domain:
        type: list
        value: "{{ item.domain }}"
        element_type: int
      value:
        type: int
        value: 0
        element_type: int
  register: cell

