---
- name: "create SEES: C{{ item.from.row }}{{ item.from.column }} -> C{{ item.to.row }}{{ item.to.column }}"
  platform42.neo4j.edge:
    neo4j_uri: "{{ NEO4J_URI }}"
    database: "{{ NEO4J_DATABASE }}"
    username: "{{ NEO4J_USERNAME }}"
    password: "{{ NEO4J_PASSWORD }}"
    type: SEES
    from:
      label: Cell
      entity_name: "C{{ item.from.row }}{{ item.from.column }}"
    to:
      label: Cell
      entity_name: "C{{ item.to.row }}{{ item.to.column }}"
    state: PRESENT
    bi_directional: True
  register: sees
